language: node_js

node_js:
  - 'node'

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/
  on:
    branch: master
