language: node_js

node_js:
  - "10.15.3" 

branches:
  only:
  - master

cache:
  - npm
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
