// export const API_PATH_PROJECT_LIST = 'https://salicml.lappis.rocks/projetos'
//export const API_PATH_PROJECT = 'https://salicml.lappis.rocks/projetos'
var base_path = 'http://localhost:3000/'
export const API_PATH_PROJECT_LIST = base_path + 'projetos_lista'
export const API_PATH_PROJECT =  base_path + 'projetos/'
